---
application:
  name: "spooney-discord-bot"
  project: "Spooney"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "spoon"
  version: "8.0"
routers:
- name: "main-spooney-discord-bot"
  routes:
  - application_name: "spooney-discord-bot"
    paths:
    - "/*"
